service: compare-yourself-sls-ts
app: compare-yourself-sls-ts
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: sa-east-1

functions:
  hello:
    handler: src/lambdas/hello.hello
    events:
      - http:
          path: /
          method: get

plugins:
  - serverless-python-requirements
